### ISSUE TITLE
similarity search

### ISSUE THREAD

**Issue by jojo05** [tinrab/go-tensorflow-image-recognition#3]
Is it possible to return the vector before the classify layer, so that it can also be used for image similarity?

thanks

**Comment by tinrab** [comment]
Running TF session results in probabilities for each label, contained inside a vector [here](https://github.com/tinrab/go-tensorflow-image-recognition/blob/master/api/main.go#L115). That's all there is. I don't know how would you calculate similarity with this. That's out of the scope here.

**Comment by jojo05** [comment]
ok, thanks
