### ISSUE TITLE
nil-operation tensorflow problem

### ISSUE THREAD

**Issue by jkuri** [tinrab/go-tensorflow-image-recognition#5]
Hi Tin! 

I am trying to run your code and when I send image via curl to the server getting following issue:
```
http: panic serving [::1]:57414: nil-Operation. If the Output was created with a Scope object, see Scope.Err() for details.
```
Please note that I did not work with TF before, so I am sorry if the answer to my issue is too obvious. 

lp :)

**Comment by tinrab** [comment]
Sorry for a late response. I got a completely different error, but now I fixed and tested it (https://github.com/tinrab/go-tensorflow-image-recognition/commit/552e650f93fc84290725a4271b8e5c5ac5cb345d).

**Comment by jkuri** [comment]
thanks, works for me now as well.
