### ISSUE TITLE
ERROR:  reference to `TF_ImportGraphDefOptionsSetDefaultDevice'

### ISSUE THREAD

**Issue by tonanuvem** [tinrab/go-tensorflow-image-recognition#7]
Step 14/15 : RUN go get ./... && go build -o /usr/bin/app .
 ---> Running in 2b689073342c
# github.com/tensorflow/tensorflow/tensorflow/go
/tmp/go-build057595270/b096/_x003.o: In function `_cgo_691d94bb61b7_Cfunc_TF_ImportGraphDefOptionsSetDefaultDevice':
/tmp/go-build/cgo-gcc-prolog:198: undefined reference to `TF_ImportGraphDefOptionsSetDefaultDevice'
collect2: error: ld returned 1 exit status
ERROR: Service 'api' failed to build: The command '/bin/sh -c go get ./... && go build -o /usr/bin/app .' returned a non-zero code: 2

**Comment by tonanuvem** [comment]
is anyone also getting this error by step 14/15?

**Comment by fardok** [comment]
> is anyone also getting this error by step 14/15?

$ go test github.com/tensorflow/tensorflow/tensorflow/go
# github.com/tensorflow/tensorflow/tensorflow/go
/usr/bin/ld: $WORK/b048/_x003.o: in function `_cgo_9c811c796559_Cfunc_TF_ImportGraphDefOptionsSetDefaultDevice':
/tmp/go-build/cgo-gcc-prolog:204: undefined reference to `TF_ImportGraphDefOptionsSetDefaultDevice'
collect2: error: ld returned 1 exit status
FAIL	github.com/tensorflow/tensorflow/tensorflow/go [build failed]

**Comment by fardok** [comment]
>go test github.com/tensorflow/tensorflow/tensorflow/go

github.com/tensorflow/tensorflow/tensorflow/go
/usr/bin/ld: $WORK/b048/_x003.o: in function `_cgo_9c811c796559_Cfunc_TF_ImportGraphDefOptionsSetDefaultDevice':
/tmp/go-build/cgo-gcc-prolog:204: undefined reference to `TF_ImportGraphDefOptionsSetDefaultDevice'
collect2: error: ld returned 1 exit status

FAIL	github.com/tensorflow/tensorflow/tensorflow/go [build failed]

**Comment by fardok** [comment]
i think its a problem with  >sudo ldconfig

linker cant find and link tensor library ((((

**Comment by tonanuvem** [comment]
could you find any work around?

**Comment by tinrab** [comment]
I've updated some dependencies and changed instructions in the [README](https://github.com/tinrab/go-tensorflow-image-recognition/blob/a964a02518261ab77b3f0cd35260c614403bcf36/README.md).

**Comment by l0r3m1p5um000** [comment]
Still getting errors..
`main.go:15:2: cannot find package "github.com/julienschmidt/httprouter" in any of:
        /usr/local/go/src/github.com/julienschmidt/httprouter (from $GOROOT)`

I was trying to install it manually in the Dockerfile, but it returned this error again.
`_cgo_9c811c796559_Cfunc_TF_ImportGraphDefOptionsSetDefaultDevice`

Additional it reports the warning `modules disabled by GO111MODULE=auto in GOPATH/src`

**Comment by tinrab** [comment]
I've made another fix inside Dockerfile. It worked for me because the `vendor` directory was being copied into the image, but the case where it isn't there was not covered.
